name: my_rpc
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  async: ^2.8.2 
  collection: ^1.15.0
  crypto: ^3.0.1
  encrypt: ^5.0.1
  logging: ^1.0.2
  path: ^1.8.0
  pointycastle: ^3.3.4

